# Generated by Django 5.2.4 on 2025-08-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buttlers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttler',
            name='user',
        ),
    ]
