# Generated by Django 5.2.4 on 2025-09-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buttlers', '0002_remove_buttler_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ButtlerFAQ',
        ),
    ]
