# Generated by Django 5.2.4 on 2025-08-01 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Brand Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Brand Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Model Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Model Slug')),
                ('code', models.CharField(max_length=100, verbose_name='Model Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Model Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'ordering': ['brand', 'name'],
                'unique_together': {('brand', 'name'), ('brand', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=36, null=True, unique=True, verbose_name='VIN Number')),
                ('license_plate', models.CharField(blank=True, max_length=16, null=True, verbose_name='License Plate')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Images')),
                ('retail_price', models.IntegerField(verbose_name='Retail Price')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Release Date')),
                ('mileage', models.IntegerField(default=0, verbose_name='Mileage')),
                ('is_sellable', models.BooleanField(default=True, verbose_name='Is Sellable')),
                ('sell_price', models.IntegerField(blank=True, null=True, verbose_name='Sell Price')),
                ('is_subscriptable', models.BooleanField(default=False, verbose_name='Is Subscriptable')),
                ('subscription_fee_1', models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (1 month)')),
                ('subscription_fee_3', models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (3 month)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_new', models.BooleanField(default=True, verbose_name='Is New')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.model', verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
