# Generated by Django 5.2.4 on 2025-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='subscription_fee_12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (12 month)'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (6 month)'),
        ),
    ]
