# Generated by Django 5.2.4 on 2025-08-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_subscription_fee_12_car_subscription_fee_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='subscription_fee_24',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (24 month)'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_36',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (36 month)'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_48',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (48 month)'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_60',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (60 month)'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_72',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (72 month)'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_84',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (84 month)'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_96',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee (96 month)'),
        ),
    ]
