# Generated by Django 5.2.4 on 2025-08-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_subscription_fee_24_car_subscription_fee_36_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='Is Hot'),
        ),
    ]
