# Generated by Django 5.2.4 on 2025-08-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_is_hot'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='buttler_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Buttler Price'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_buttler',
            field=models.BooleanField(default=False, verbose_name='Is Buttler'),
        ),
    ]
