# Generated by Django 5.2.4 on 2025-09-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_buttler_price_car_is_buttler'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='car',
            name='sub_model',
            field=models.CharField(blank=True, null=True, verbose_name='Sub Model'),
        ),
    ]
