# Generated by Django 5.2.4 on 2025-09-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_color_car_sub_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.CharField(blank=True, null=True, verbose_name='Trim'),
        ),
    ]
