# Generated by Django 5.2.4 on 2025-09-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_trim'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='inspection_report',
            field=models.URLField(blank=True, null=True, verbose_name='Inspection Report'),
        ),
    ]
