# Generated by Django 5.2.4 on 2025-09-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_inspection_report'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('brand', 'slug')},
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Brand Slug'),
        ),
        migrations.AlterField(
            model_name='model',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model Code'),
        ),
        migrations.AlterField(
            model_name='model',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Model Slug'),
        ),
    ]
