# Generated by Django 5.2.4 on 2025-09-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_model_unique_together_alter_brand_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='subscription_available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Available From'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_fee_minimum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Fee Minimum'),
        ),
    ]
