# Generated by Django 5.2.4 on 2025-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_subscription_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='front_image',
            field=models.URLField(blank=True, null=True, verbose_name='Model Front Image URL'),
        ),
        migrations.AddField(
            model_name='model',
            name='rear_image',
            field=models.URLField(blank=True, null=True, verbose_name='Model Rear Image URL'),
        ),
    ]
