# Generated by Django 5.2.4 on 2025-09-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_model_front_image_model_rear_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='buttler_price',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_buttler',
        ),
        migrations.AddField(
            model_name='car',
            name='butler_available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Butler Available From'),
        ),
        migrations.AddField(
            model_name='car',
            name='butler_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Butler Price'),
        ),
        migrations.AddField(
            model_name='car',
            name='butler_reservated_dates',
            field=models.JSONField(blank=True, null=True, verbose_name='Butler Reservated Dates'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_butler',
            field=models.BooleanField(default=False, verbose_name='Is Butler'),
        ),
    ]
