# Generated by Django 5.2.4 on 2025-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_car_buttler_price_remove_car_is_buttler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='butler_price',
        ),
        migrations.AddField(
            model_name='car',
            name='butler_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Butler Fee'),
        ),
        migrations.AddField(
            model_name='car',
            name='butler_overtime_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Butler Overtime Fee'),
        ),
    ]
