# Generated by Django 5.2.4 on 2025-10-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_car_butler_price_car_butler_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('LPG', 'LPG')], default='GASOLINE', verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='car',
            name='subscription_overmileage_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Subscription Overmileage Fee'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='AUTOMATIC', verbose_name='Transmission Type'),
        ),
    ]
