# Generated by Django 5.2.4 on 2025-10-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_car_fuel_type_car_subscription_overmileage_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive_type',
            field=models.CharField(choices=[('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive'), ('AWD', 'All Wheel Drive')], default='FWD', verbose_name='Drive Type'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Engine Size'),
        ),
        migrations.AddField(
            model_name='car',
            name='passenger_count',
            field=models.IntegerField(default=5, verbose_name='Passenger Count'),
        ),
    ]
