# Generated by Django 5.2.4 on 2025-10-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_car_drive_type_car_engine_size_car_passenger_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Is Imported'),
        ),
        migrations.AddField(
            model_name='car',
            name='acquisition_tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Acquisition Tax'),
        ),
        migrations.AddField(
            model_name='car',
            name='tax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tax'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.IntegerField(default=2000, verbose_name='Engine Size'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_sellable',
            field=models.BooleanField(default=False, verbose_name='Is Sellable'),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date'),
        ),
    ]
