# Generated by Django 5.2.4 on 2025-09-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='service',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler'), ('SALE', 'Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='service',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler'), ('SALE', 'Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faq',
            name='service',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler'), ('SALE', 'Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='service',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler'), ('SALE', 'Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='service',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler'), ('SALE', 'Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='term',
            name='service',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler'), ('SALE', 'Sale')], max_length=20),
        ),
    ]
