# Generated by Django 5.2.4 on 2025-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_ad_service_alter_event_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='background_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
