# Generated by Django 5.2.4 on 2025-09-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_ad_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler'), ('SALE', 'Sale')], max_length=20)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'GPTPrompt',
                'verbose_name_plural': 'GPTPrompts',
            },
        ),
    ]
