# Generated by Django 5.2.4 on 2025-09-30 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_gptprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gptprompt',
            options={'verbose_name': 'GPT Prompt', 'verbose_name_plural': 'GPT Prompts'},
        ),
    ]
