# Generated by Django 5.2.4 on 2025-08-25 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('usage_limit', models.IntegerField(default=1, verbose_name='Usage Limit')),
                ('usage_limit_per_user', models.IntegerField(default=1, verbose_name='Usage Limit Per User')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Point Coupon',
                'verbose_name_plural': 'Point Coupons',
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('COUPON', 'Coupon'), ('REFERRAL', 'Referral'), ('WITHDRAW', 'Withdraw'), ('DEPOSIT', 'Deposit'), ('REVIEW', 'Review'), ('COMMENT', 'Comment'), ('ACTIVITY', 'Activity'), ('CANCEL', 'Cancel'), ('SERVICE', 'Service'), ('OTHER', 'Other'), ('SUBSCRIPTION', 'Subscription'), ('BUTTLER', 'Buttler')], max_length=20)),
                ('transaction_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
            },
        ),
    ]
