# Generated by Django 5.2.4 on 2025-08-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pointcoupon_pointtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
