# Generated by Django 5.2.4 on 2025-10-01 00:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pointtransaction_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed'), ('FREE', 'Free')], default='PERCENTAGE', max_length=20)),
                ('discount_rate', models.IntegerField(blank=True, null=True, verbose_name='Discount Rate')),
                ('max_discount', models.IntegerField(default=700000, verbose_name='Max Discount Amount')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Discount Amount')),
                ('min_price', models.IntegerField(default=0, verbose_name='Min Subscription Price')),
                ('max_price', models.IntegerField(default=1000000000, verbose_name='Max Subscription Price')),
                ('min_month', models.IntegerField(default=1, verbose_name='Min Month')),
                ('max_month', models.IntegerField(default=12, verbose_name='Max Month')),
                ('usage_limit', models.IntegerField(default=1, verbose_name='Usage Limit')),
                ('usage_limit_per_user', models.IntegerField(default=1, verbose_name='Usage Limit Per User')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Rule',
                'verbose_name_plural': 'Referral Rules',
            },
        ),
    ]
