# Generated by Django 5.2.4 on 2025-10-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_referralrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('COUPON', 'Coupon'), ('REFERRAL', 'Referral'), ('WITHDRAW', 'Withdraw'), ('DEPOSIT', 'Deposit'), ('REVIEW', 'Review'), ('COMMENT', 'Comment'), ('ACTIVITY', 'Activity'), ('CANCEL', 'Cancel'), ('SERVICE', 'Service'), ('OTHER', 'Other'), ('SUBSCRIPTION', 'Subscription'), ('BUTLER', 'Butler')], max_length=20),
        ),
    ]
