# Generated by Django 5.2.4 on 2025-08-01 11:31

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('name', models.CharField(max_length=24)),
                ('username', models.CharField(blank=True, max_length=24, unique=True)),
                ('ci', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True))),
                ('ci_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_business', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='PassVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_no', models.CharField(max_length=50, unique=True)),
                ('token_version_id', models.CharField(max_length=50)),
                ('key', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('iv', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('hmac_key', django_cryptography.fields.encrypt(models.CharField(max_length=100))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pass Verification',
                'verbose_name_plural': 'Pass Verifications',
                'db_table': 'PassVerification',
                'indexes': [models.Index(fields=['req_no'], name='PassVerific_req_no_b2e41a_idx'), models.Index(fields=['token_version_id'], name='PassVerific_token_v_e2f6ce_idx'), models.Index(fields=['created_at'], name='PassVerific_created_2d65ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mobile', 'Mobile'), ('email', 'Email')], max_length=10)),
                ('target', models.CharField(max_length=255)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('type', 'target')},
            },
        ),
        migrations.CreateModel(
            name='UserSocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver'), ('apple', 'Apple')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Social Account',
                'verbose_name_plural': 'User Social Accounts',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
