# Generated by Django 5.2.4 on 2025-09-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassVerification',
        ),
    ]
