# Generated by Django 5.2.4 on 2025-08-03 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.TextField(verbose_name='Model')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Request',
                'verbose_name_plural': 'Model Requests',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField(verbose_name='Month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Request',
                'verbose_name_plural': 'Subscription Requests',
            },
        ),
    ]
