# Generated by Django 5.2.4 on 2025-08-07 03:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('brand_ids', models.JSONField(blank=True, default=list, verbose_name='Brand IDs')),
                ('model_ids', models.JSONField(blank=True, default=list, verbose_name='Model IDs')),
                ('car_ids', models.JSONField(blank=True, default=list, verbose_name='Car IDs')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed'), ('FREE', 'Free')], default='PERCENTAGE', max_length=20)),
                ('discount_rate', models.IntegerField(blank=True, null=True, verbose_name='Discount Rate')),
                ('max_discount', models.IntegerField(default=1000000000, verbose_name='Max Discount Amount')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Discount Amount')),
                ('min_price', models.IntegerField(default=0, verbose_name='Min Subscription Price')),
                ('max_price', models.IntegerField(default=1000000000, verbose_name='Max Subscription Price')),
                ('min_month', models.IntegerField(default=1, verbose_name='Min Month')),
                ('max_month', models.IntegerField(default=12, verbose_name='Max Month')),
                ('usage_limit', models.IntegerField(default=1, verbose_name='Usage Limit')),
                ('usage_limit_per_user', models.IntegerField(default=1, verbose_name='Usage Limit Per User')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valid From')),
                ('valid_to', models.DateTimeField(verbose_name='Valid To')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='subscriptions.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Coupon',
                'verbose_name_plural': 'User Coupons',
            },
        ),
    ]
