# Generated by Django 5.2.4 on 2025-08-07 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_coupon_usercoupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.usercoupon'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='subscriptions.usercoupon'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'coupon')},
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionrequest',
            unique_together={('user', 'coupon')},
        ),
    ]
