# Generated by Django 5.2.4 on 2025-08-21 04:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_subscription_fee_24_car_subscription_fee_36_and_more'),
        ('subscriptions', '0005_subscription_coupon_subscriptionrequest_coupon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupon',
            new_name='SubscriptionCoupon',
        ),
        migrations.RenameModel(
            old_name='FAQ',
            new_name='SubscriptionFAQ',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='SubscriptionLike',
        ),
        migrations.RenameModel(
            old_name='ModelRequest',
            new_name='SubscriptionModelRequest',
        ),
        migrations.RenameModel(
            old_name='Review',
            new_name='SubscriptionReview',
        ),
        migrations.RenameModel(
            old_name='ReviewLike',
            new_name='SubscriptionReviewLike',
        ),
        migrations.RenameModel(
            old_name='UserCoupon',
            new_name='SubscriptionUserCoupon',
        ),
    ]
