# Generated by Django 5.2.4 on 2025-08-22 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_rename_request_generalrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalrequest',
            options={'verbose_name': 'General Request', 'verbose_name_plural': 'General Requests'},
        ),
        migrations.AddField(
            model_name='generalrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generalrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
