# Generated by Django 5.2.4 on 2025-08-25 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_generalrequest_options_and_more'),
        ('users', '0003_pointtransaction_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionrequest',
            unique_together={('user', 'coupon')},
        ),
        migrations.AddField(
            model_name='subscription',
            name='request',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscriptions.subscriptionrequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='users.pointtransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionrequest',
            unique_together={('user', 'coupon'), ('user', 'point')},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='car',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='coupon',
        ),
    ]
