# Generated by Django 5.2.4 on 2025-08-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='billing_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
