# Generated by Django 5.2.4 on 2025-08-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_remove_subscription_end_remove_subscription_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
