# Generated by Django 5.2.4 on 2025-09-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_remove_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionFAQ',
        ),
        migrations.DeleteModel(
            name='GeneralRequest',
        ),
    ]
