# Generated by Django 5.2.4 on 2025-09-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_remove_generalrequest_user_delete_subscriptionfaq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='auth_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='customer_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
