# Generated by Django 5.2.4 on 2025-10-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('subscriptions', '0015_subscriptionrequest_auth_key_and_more'),
        ('users', '0005_alter_pointtransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Payment Date'),
        ),
        migrations.AddField(
            model_name='subscriptionrequest',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='payments.billing'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='coupon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='subscriptions.subscriptionusercoupon'),
        ),
        migrations.AlterField(
            model_name='subscriptionrequest',
            name='point',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='users.pointtransaction'),
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='auth_key',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='billing_key',
        ),
        migrations.RemoveField(
            model_name='subscriptionrequest',
            name='customer_key',
        ),
    ]
