# Generated by Django 5.2.4 on 2025-10-27 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_merchant_id'),
        ('subscriptions', '0016_alter_subscriptionrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='payments.payment'),
        ),
    ]
