# Generated by Django 5.2.4 on 2025-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_subscriptionrequest_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='schedule_payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Schedule Payment Date'),
        ),
    ]
