# Generated by Django 5.2.4 on 2025-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butlers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='butlerrequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
