# Generated by Django 5.2.4 on 2025-10-06 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('butlers', '0002_butlerrequest_description'),
        ('subscriptions', '0015_subscriptionrequest_auth_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender', models.CharField(choices=[('TOSS', 'Toss'), ('PORTONE', 'PortOne')], max_length=20)),
                ('customer_key', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_key', models.CharField(max_length=255)),
                ('card_company', models.CharField(blank=True, max_length=50, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_type', models.CharField(blank=True, max_length=10, null=True)),
                ('card_owner_type', models.CharField(blank=True, max_length=10, null=True)),
                ('card_issuer_code', models.CharField(blank=True, max_length=2, null=True)),
                ('card_acquirer_code', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vender', models.CharField(choices=[('TOSS', 'Toss'), ('PORTONE', 'PortOne')], max_length=20)),
                ('payment_key', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('WAITING_FOR_DEPOSIT', 'Waiting For Deposit'), ('DONE', 'Done'), ('CANCELED', 'Canceled'), ('PARTIAL_CANCELED', 'Partial Canceled'), ('ABORTED', 'Aborted'), ('EXPIRED', 'Expired')], max_length=20)),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('BILLING', 'Billing'), ('BRANDPAY', 'BrandPay')], max_length=20)),
                ('order_id', models.CharField(max_length=64)),
                ('order_name', models.CharField(max_length=100)),
                ('merchant_id', models.CharField(max_length=14)),
                ('currency', models.CharField(max_length=20)),
                ('method', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.IntegerField()),
                ('balance_amount', models.IntegerField()),
                ('supplied_amount', models.IntegerField()),
                ('vat', models.IntegerField()),
                ('tax_exemption_amount', models.IntegerField(default=0)),
                ('tax_free_amount', models.IntegerField(default=0)),
                ('card_issuer_code', models.CharField(blank=True, max_length=2, null=True)),
                ('card_acquirer_code', models.CharField(blank=True, max_length=2, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_installment_plan_months', models.IntegerField(blank=True, null=True)),
                ('card_is_interest_free', models.BooleanField(blank=True, null=True)),
                ('card_interest_payer', models.CharField(blank=True, max_length=20, null=True)),
                ('card_approve_no', models.CharField(blank=True, max_length=8, null=True)),
                ('card_use_card_point', models.BooleanField(blank=True, null=True)),
                ('card_type', models.CharField(blank=True, max_length=10, null=True)),
                ('card_owner_type', models.CharField(blank=True, max_length=10, null=True)),
                ('card_acquire_status', models.CharField(blank=True, max_length=20, null=True)),
                ('card_amount', models.IntegerField(blank=True, null=True)),
                ('easypay_provider', models.CharField(blank=True, max_length=50, null=True)),
                ('easypay_amount', models.IntegerField(blank=True, null=True)),
                ('easypay_discount_amount', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(default='KR', max_length=2)),
                ('is_partial_cancelable', models.BooleanField(default=True)),
                ('use_escrow', models.BooleanField(default=False)),
                ('culture_expense', models.BooleanField(default=False)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('checkout_url', models.URLField(blank=True, null=True)),
                ('last_transaction_key', models.CharField(blank=True, max_length=64, null=True)),
                ('secret', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.CharField(default='2022-11-16', max_length=20)),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('billing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.billing')),
                ('butler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='butlers.butler')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
