# Generated by Django 5.2.4 on 2025-10-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='merchant_id',
            field=models.CharField(max_length=64),
        ),
    ]
